[general]
OPENAI_API_KEY = "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"
PINECONE_API_KEY = "pcsk_77Mnm8_NQVjdoykkLdzPkuGmcbfN1MJ2kUK3u64iZMyxGVwFpvCEwkg7K6u17pGFfqRRXD"
PINECONE_ENVIRONMENT = "us-east1-gcp"
